// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSExtensionsExportImport
{
    static class Vsix
    {
        public const string Id = "1af89e05-b2dc-49ec-8e91-1521f83f7467";
        public const string Name = "VS Extensions Export/Import";
        public const string Description = @"Provides the ability to Export the list of Visual Studio extensions and then Import the updated and compatible versions of the extensions. ";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Vivian Lobo";
        public const string Tags = "visual studio, extensions, import, export";
    }
}
