// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.188
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSExtensionsExportImport
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSExtensionsExportImportCommandPackageString = "7224556f-1244-48ea-b51a-5a3a446733e2";
        public const string guidVSExtensionsExportImportCommandPackageCmdSetString = "316ab650-ebaf-45f8-81eb-71f75d36dd2d";
        public const string guidImagesString = "aa21f4ea-2a18-4d59-bdf4-e5f7cfaa1c27";
        public static Guid guidVSExtensionsExportImportCommandPackage = new Guid(guidVSExtensionsExportImportCommandPackageString);
        public static Guid guidVSExtensionsExportImportCommandPackageCmdSet = new Guid(guidVSExtensionsExportImportCommandPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int VSExtensionsExportImportCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
